name: 'softwares_market'

services:
  postgres_db:
    container_name: postgres_softwaresMarketDb2
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 32167
      POSTGRES_DB: softwaresMarketDb2
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
